description: Desenhe, desenvolva e publique APIs para conectar softwares da empresa no seu produto.

name: skynet-dotnet-stack

displayName: Stack API

picture: "stack.png"

category: Backend

compatibility:
  - net5.0
  - net6.0

technologies: [".NET", "C#", "Api", "OpenAPI", "Splunk", "Prometheus", "Jaeger", "AWS SQS", "AWS DynamoDB", "Docker", "AWS ECS/Fargate"]

about: about.md

useCase: useCase.md